version: '3.8'

services:
  pjx-sso-identityserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pjx-sso-identityserver
    ports:
      - 5001:80
      - 5002:443
    networks:
      - pjx-network
    environment:
      - PJX_SSO__CERTIFICATE=pjx-sso-identityserver.rsa_2048.cert.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/pjx-sso-identityserver.rsa_2048.cert.pfx

networks:
  pjx-network:
    name: pjx-network
    driver: bridge
